### PR TITLE
John Trial to fix all significant performance issues and bugs

### PR DESCRIPTION
**Pull request by marios-pz**
TODO OF DEV BRANCH
- [x] Purge Custom mouse icon
- [x] optimize open_world
- [x] turn unnecessary methods of gamestate to functions to utils
- [x] turn unnecessary method load_sprite of enemy class into a function to utils
- [x] remove useless `self.player` from enemy parameters
- [x] fix boss hitbox
- [x] fix boss stuck
- [x] clean up unnecessary code in `PauseMenu` class
- [x] remove useless `self.screen` from `QuestUI` parameters
- [x] remove useless `self.screen` from `QuestManager` parameters
- [x] remove useless `self.screen` from `CutsceneManager` parameters
- [x] remove useless `self.screen` from `Menu` parameters
- [x] remove useless `self.screen` from `Enemy` parameters
- [x] remove useless `self.screen` from `Level` parameters
- [x] if statement loop hole in Training Field, HIGH PRIORITY ISSUE
- [x] make cutscenes scenes a bit faster
- [x] player needs a getting hit sound effect
- [x] sword attack needs a new sound
- [x] change music when visiting `cave_garden`
- [x] saving system is missing, when player exits it has to saves his data
- [x] coins missing from inventory screen

### CODE REVIEW

**Comment by marios-pz** [comment]
TODO Fix the below inconvenience:

`self` has its own screen attribute, yet I pass a clone as another parameter 

Screenshot 2022-10-16 at 9 40 16 PM

**Comment by mariospapaz** [comment]
Boss is stuck for no reason, I have to check the main branch

**Comment by mariospapaz** [comment]
An whoopsie occurred and the enemies thinks , furniture such as roads contain hitboxes, therefore its stops moving

**Comment by marios-pz** [comment]
Now that enemies are lot more readable, we can finally move in fixing training field.
After that we can freely remake Cave Levels

**Comment by marios-pz** [comment]
Python 3.11 is getting released in 26th.
Until pygame devs release a `working` release for that version, I am confident that the PR will be merged by then

**Comment by marios-pz** [comment]
Whew, lots of work today.

**Comment by marios-pz** [comment]
TODO Plan is done, now I have to make new cave levels. 

Let's hope I find more optimizations in the way.

## Cave Level Redesign
- [x] wall_chunk function broke during this PR
- [x] reduce the 2 cave rooms in many small rooms 

# Other bugs found
- [x] Spawning systems on game boot are acting up (since I added a saving feature its important to fix this)
- [x] REDACTED needs repositioning
- [x]  Stop enemies from chasing the player when he is out of distance (accidentally recreated this bug)
- [x]  Put back corresponding music to all levels

**Comment by marios-pz** [comment]
New TODO:

Decorate = walls, enemies, torches, etc
- [x] Add missing hp_potion images to chests
- [x] Decorate Cave Room 1
- [x] Decorate Cave Room 2
- [x] Decorate Cave Room 3
- [x] Decorate Cave Room 4
- [x] Decorate Cave Room 5
- [x] Decorate Cave Room 6
- [x] Decorate Cave Room 7
- [x] Decorate Cave Room 8
- [x] Decorate Cave Room 9

**Comment by marios-pz** [comment]
Technically I am done with this PR. But I cannot merge it yet as I have finished sooner than the release of Pygame for Python 3.11

**Comment by marios-pz** [comment]
- [x] Tweak cutscenes to our need

**Comment by mariospapaz** [comment]
This week TODO:

- [ ] pygbag shows unresonable pygame errors 
- [ ] random permanent frame drop to 35 fps after completing training field
- [ ] some enemy attacking distances need some balancing

**Comment by marios-pz** [comment]
New stable pygame release is not ready but I can somewhat play John in 3.11 now!
Sorry for the delay, but it needs more patience

**Comment by mariospapaz** [comment]
The game will be released upon release of stable pygame and we will not wait for further pygbag updates sadly

**Pull request merged**
